
SET "PYTHON_CONFIG=Python\PATH.txt"
SET /P PATH_PYTHON= < "%PYTHON_CONFIG%"
IF NOT EXIST "%PATH_PYTHON%\python.exe" (
  ECHO python.exe not found
  EXIT /B 1
)
IF NOT DEFINED GITHUB_ENV (
  ECHO not in a github action environment
  EXIT /B 1
)
ECHO PATH_PYTHON=%PATH_PYTHON%
ECHO PATH_PYTHON=%PATH_PYTHON%> "%GITHUB_ENV%"
ECHO PATH=%PATH_PYTHON%;%PATH%
ECHO PATH=%PATH_PYTHON%;%PATH%> "%GITHUB_ENV%"
TYPE %GITHUB_ENV%
