
name: Manual Dispatch (Linux)

on:
  
  workflow_dispatch:

jobs:
  
  "Job_Ubuntu":
    
    runs-on: ubuntu-22.04
    ## https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories
    ## https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2204-Readme.md

    steps:
      
      - name: Checkout
        uses: actions/checkout@v4
        ## https://github.com/actions/checkout

      - name: Run a multi-line script
        run: |
          which -a bash
          which -a java
          java --version
          java --help
