
name: Manual Dispatch (Linux)

on:
  
  workflow_dispatch:

jobs:
  
  build:
    
    runs-on: ubuntu-latest

    steps:
      
      - uses: actions/checkout@v4
        ## https://github.com/actions/checkout

      - name: Run a multi-line script
        run: |
          which -a java
          java --version
          java --help
