
name: FontForge
run-name: FontForge

on:
  
  schedule:
    # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule
    - cron:  '46 5  *  *  FRI'
          #   │  │  │  │  │
          #   │  │  │  │  └─── day of the week  (0–6, SUN-SAT)
          #   │  │  │  └────── month            (1–12)
          #   │  │  └───────── day of the month (1–31)
          #   │  └──────────── hour             (0–23)
          #   └─────────────── minute           (0–59)

  push:
    # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#push
    branches:
      - 'main'
    paths:
      - 'FontForge/**.*'

  workflow_dispatch:

jobs:

  Download-Font:
    
    runs-on: ubuntu-22.04
      ## https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories
      ## https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2204-Readme.md
    environment: FontCJK

    steps:
      
      - name: Checkout
        uses: actions/checkout@v4
          ## https://github.com/actions/checkout

      - name: List Artifacts
        env:
          REPOSITORY_FROM : "${{ secrets.REPOSITORY_FONT_FROM }}"
          WORKFLOW_NAME   : "${{ secrets.WORKFLOW_NAME_FONT }}"
        working-directory: FontForge/
        shell: bash
          ## https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_iddefaultsrunshell
        run: |
          bash Script/Bash/GetFontCJK.sh

      - uses: actions/download-artifact@v4
        ## https://github.com/actions/download-artifact
        with:
          path           : FontForge/Artifact/
          pattern        : "font-*"
          merge-multiple : false
          github-token   : "${{ github.token }}"
          repository     : "${{ secrets.REPOSITORY_FONT_FROM }}"
          run-id         : "${{ env.ARTIFACT_RUN_ID }}"


