
name: Hadoop
run-name: Hadoop

on:
  
  schedule:
    # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule
    - cron:  '54 6  *  *  TUE'
          #   │  │  │  │  │
          #   │  │  │  │  └─── day of the week  (0–6, SUN-SAT)
          #   │  │  │  └────── month            (1–12)
          #   │  │  └───────── day of the month (1–31)
          #   │  └──────────── hour             (0–23)
          #   └─────────────── minute           (0–59)

  push:
    # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#push
    branches:
      - 'main'
    paths:
      - 'Hadoop/**.*'

  workflow_dispatch:
    inputs:
      ## https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories
      system-linux:
        description: 'Linux Version'
        required: true
        default: 'ubuntu-latest'
        type: choice
        options:
        - ubuntu-latest
        - ubuntu-24.04
        - ubuntu-22.04
        - ubuntu-20.04

jobs:

  Get-URL-Hadoop-Release:
    runs-on: ${{ inputs.system-linux || 'ubuntu-latest' }}
      ## https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories
      ## https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2204-Readme.md
    # Map a step output to a job output
    outputs:
      dowload-url: ${{ steps.step-output.outputs.URL_DOWNLOAD }}
      sha512-url:  ${{ steps.step-output.outputs.URL_SHA512 }}
      asc-url:     ${{ steps.step-output.outputs.URL_ASC }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
          ## https://github.com/actions/checkout

      - name: Test
        working-directory: Hadoop/
        shell: bash
          ## https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_iddefaultsrunshell
        run: |
          bash Bash/TestSystem.sh
          bash Bash/TestEnvironment.sh

      - id: step-output
        name: Get Download URL
        working-directory: Hadoop/
        shell: bash
          ## https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_iddefaultsrunshell
        run: |
          bash Bash/GetURL-HADOOP-Release.sh

  Get-URL-Hadoop-Common:
    runs-on: ${{ inputs.system-linux || 'ubuntu-latest' }}
      ## https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories
      ## https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2204-Readme.md
    # Map a step output to a job output
    outputs:
      url-latest: ${{ steps.step-output.outputs.URL_LATEST }}
      url-stable: ${{ steps.step-output.outputs.URL_STABLE }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
          ## https://github.com/actions/checkout

      - name: Test
        working-directory: Hadoop/
        shell: bash
          ## https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_iddefaultsrunshell
        run: |
          bash Bash/TestSystem.sh
          bash Bash/TestEnvironment.sh

      - id: step-output
        name: Get Download URL
        working-directory: Hadoop/
        shell: bash
          ## https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_iddefaultsrunshell
        run: |
          bash Bash/GetURL-HADOOP-Common.sh

  Get-URL-Hadoop-Common-Latest:
    runs-on: ${{ inputs.system-linux || 'ubuntu-latest' }}
      ## https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories
      ## https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2204-Readme.md
    needs: 
    - Get-URL-Hadoop-Common
    # Map a step output to a job output
    outputs:
      dowload-url: ${{ steps.step-output.outputs.URL_DOWNLOAD }}
      sha512-url:  ${{ steps.step-output.outputs.URL_SHA512 }}
      asc-url:     ${{ steps.step-output.outputs.URL_ASC }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
          ## https://github.com/actions/checkout

      - id: step-output
        name: Get Download URL
        working-directory: Hadoop/
        env:
          URL_FILES: "${{ needs.Get-URL-Hadoop-Common.outputs.url-latest }}"
        shell: bash
          ## https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_iddefaultsrunshell
        run: |
          bash Bash/GetURL-HADOOP-Common2.sh

  Get-URL-Hadoop-Common-Stable:
    runs-on: ${{ inputs.system-linux || 'ubuntu-latest' }}
      ## https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories
      ## https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2204-Readme.md
    needs: 
    - Get-URL-Hadoop-Common
    # Map a step output to a job output
    outputs:
      dowload-url: ${{ steps.step-output.outputs.URL_DOWNLOAD }}
      sha512-url:  ${{ steps.step-output.outputs.URL_SHA512 }}
      asc-url:     ${{ steps.step-output.outputs.URL_ASC }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
          ## https://github.com/actions/checkout

      - id: step-output
        name: Get Download URL
        working-directory: Hadoop/
        env:
          URL_FILES: "${{ needs.Get-URL-Hadoop-Common.outputs.url-stable }}"
        shell: bash
          ## https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_iddefaultsrunshell
        run: |
          bash Bash/GetURL-HADOOP-Common2.sh

  Download-Package-Hadoop:
    runs-on: ${{ inputs.system-linux || 'ubuntu-latest' }}
      ## https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories
      ## https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2204-Readme.md
    needs: 
    - Get-URL-Hadoop-Release
    - Get-URL-Hadoop-Common-Latest
    - Get-URL-Hadoop-Common-Stable

    steps:
      - name: Checkout
        uses: actions/checkout@v4
          ## https://github.com/actions/checkout

      - name: Test
        working-directory: Hadoop/
        env:
          URL_DOWNLOAD: "${{ needs.Get-URL-Hadoop-Release.outputs.dowload-url }}"
        shell: bash
          ## https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_iddefaultsrunshell
        run: |
          echo "${URL_DOWNLOAD}"
