
name: Node
run-name: Node Jobs

on:
  
  schedule:
    # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule
    - cron:  '45 3  *  *  MON'
          #   │  │  │  │  │
          #   │  │  │  │  └─── day of the week  (0–6, SUN-SAT)
          #   │  │  │  └────── month            (1–12)
          #   │  │  └───────── day of the month (1–31)
          #   │  └──────────── hour             (0–23)
          #   └─────────────── minute           (0–59)

  push:
    # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#push
    branches:
      - 'main'
    paths:
      - 'Node/**.*'

  workflow_dispatch:
    inputs:
      ## https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories
      system-windows:
        description: 'Windows Version'
        required: true
        default: 'windows-latest'
        type: choice
        options:
        - windows-latest
        - windows-2025
        - windows-2022
        - windows-2019
      system-macos:
        description: 'macOS Version'
        required: true
        default: 'macos-latest'
        type: choice
        options:
        - macos-latest
        - macos-14
        - macos-15
      system-linux:
        description: 'Linux Version'
        required: true
        default: 'ubuntu-latest'
        type: choice
        options:
        - ubuntu-latest
        - ubuntu-24.04
        - ubuntu-22.04
        - ubuntu-20.04

jobs:

  Releases-Information:
    
    runs-on: ${{ inputs.system-linux || 'ubuntu-latest' }}
      ## https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories
      ## https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2404-Readme.md
    environment: CURL
    outputs:
      node-version: ${{ steps.releases-information.outputs.NODE_VERSION }}

    steps:
      
      - name: Checkout
        uses: actions/checkout@v4
          ## https://github.com/actions/checkout

      - id: releases-information
        name: Get Releases Data
        working-directory: Node/
        shell: bash
          ## https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_iddefaultsrunshell
        run: |
          bash Bash/Check-Releases.sh

      - name: Upload Artifact - Releases
        uses: actions/upload-artifact@v4
          ## https://github.com/actions/upload-artifact?tab=readme-ov-file#inputs
        with:
          name: Releases
          path: |
            Node/Releases/*.*

  Windows-Latest:
    runs-on: ${{ inputs.system-windows || 'windows-latest' }}
      ## https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories
      ## https://github.com/actions/runner-images/blob/main/images/windows/Windows2025-Readme.md
    needs: 
      - Releases-Information

    steps:
      
      - name: Checkout
        uses: actions/checkout@v4
          ## https://github.com/actions/checkout

      - name: Get Zip
        working-directory: Node\
        env:
          NODE_VERSION: ${{needs.Releases-Information.outputs.node-version}}
        shell: pwsh
          ## https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_iddefaultsrunshell
        run: |
          .\PowerShell\Download-Zip.ps1

      - name: Upload Artifact - x64
        if  : ${{ env.ArtifactName != '' }}
        uses: actions/upload-artifact@v4
          ## https://github.com/actions/upload-artifact?tab=readme-ov-file#inputs
        with:
          name: ${{ env.ArtifactName }}
          path: |
            Node\Unzipped\

      - name: Upload Artifact - latest
        if  : ${{ env.ArtifactName != '' }}
        uses: actions/upload-artifact@v4
          ## https://github.com/actions/upload-artifact?tab=readme-ov-file#inputs
        with:
          name: node-latest-win-x64
          path: |
            Node\Unzipped\

  macOS-Latest:
    runs-on: ${{ inputs.system-macos || 'macos-latest' }}
      ## https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories
      ## https://github.com/actions/runner-images/blob/main/images/macos/macos-15-arm64-Readme.md
    needs: 
      - Releases-Information

    steps:
      
      - name: Checkout
        uses: actions/checkout@v4
          ## https://github.com/actions/checkout

      - name: Get Package
        working-directory: Node/
        env:
          NODE_VERSION: ${{needs.Releases-Information.outputs.node-version}}
        shell: bash
          ## https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_iddefaultsrunshell
        run: |
          bash Bash/

      - name: Upload Artifact - arm64
        if  : ${{ env.ArtifactName != '' }}
        uses: actions/upload-artifact@v4
          ## https://github.com/actions/upload-artifact?tab=readme-ov-file#inputs
        with:
          name: ${{ env.ArtifactName }}
          path: |
            Node/Unzipped/
