
name: PostgreSQL
run-name: PostgreSQL

on:
  
  schedule:
    # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule
    - cron:  '45 6  *  *  FRI'
          #   │  │  │  │  │
          #   │  │  │  │  └─── day of the week  (0–6, SUN-SAT)
          #   │  │  │  └────── month            (1–12)
          #   │  │  └───────── day of the month (1–31)
          #   │  └──────────── hour             (0–23)
          #   └─────────────── minute           (0–59)

  push:
    # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#push
    branches:
      - 'main'
    paths:
      - 'PostgreSQL/**.*'

  workflow_dispatch:
    inputs:
      ## https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories
      system-linux:
        description: 'Linux Version'
        required: true
        default: 'ubuntu-latest'
        type: choice
        options:
        - ubuntu-latest
        - ubuntu-24.04
        - ubuntu-22.04
        - ubuntu-20.04

jobs:

  Download-JDBC:

    runs-on: ${{ inputs.system-linux || 'ubuntu-latest' }}
      ## https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories
      ## https://github.com/actions/runner-images/tree/main/images/ubuntu

    steps:
      
      - name: Checkout
        uses: actions/checkout@v4
          ## https://github.com/actions/checkout

      - name: Get Download URL
        working-directory: PostgreSQL/JDBC/
        shell: bash
          ## https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_iddefaultsrunshell
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            ## https://docs.github.com/en/actions/security-for-github-actions/security-guides/automatic-token-authentication#using-the-github_token-in-a-workflow
        run: |
          bash Bash/Github_Download_URL.sh

      - name: Download
        working-directory: PostgreSQL/JDBC/
        shell: bash
          ## https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_iddefaultsrunshell
        run: |
          FOLDER_ART='Artifact/'
          mkdir --parent "${FOLDER_ART}"
          FILE_NAME="${URL_DOWNLOAD##*/}"
          FILE_SAVE="${FOLDER_ART%/}/${FILE_NAME}"
          curl --output "${FILE_SAVE}" --location "${URL_DOWNLOAD}"

      - uses: actions/upload-artifact@v4
          ## https://github.com/actions/upload-artifact
        with:
          name: postgresql-jdbc-latest
          path: PostgreSQL/JDBC/Artifact/

      - uses: actions/upload-artifact@v4
          ## https://github.com/actions/upload-artifact
        with:
          name: "${{ env.NAME_PACKAGE }}"
          path: PostgreSQL/JDBC/Artifact/

  Normal-Development:

    runs-on: ${{ inputs.system-linux || 'ubuntu-latest' }}
      ## https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories
      ## https://github.com/actions/runner-images/tree/main/images/ubuntu
    environment: PostgreSQL1
    needs: [Download-JDBC]

    steps:
      
      - name: Checkout
        uses: actions/checkout@v4
          ## https://github.com/actions/checkout

      - uses: actions/download-artifact@v4
          ## https://github.com/actions/download-artifact
        with:
          # Name of the artifact to download.
          name: postgresql-jdbc-latest
          # Destination path. Supports basic tilde expansion.
          path: PostgreSQL/DevelopmentKit/

      - name: Check Environment
        working-directory: PostgreSQL/
        shell: bash
          ## https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_iddefaultsrunshell
        run: |
          bash Script/Bash/CheckEnvironment.sh

      - name: Compile
        working-directory: PostgreSQL/
        shell: bash
          ## https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_iddefaultsrunshell
        run: |
          bash Script/Bash/Compile.sh

      - name: Testing
        working-directory: PostgreSQL/
        shell: bash
          ## https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_iddefaultsrunshell
        env:
          PG_SERVER_URL      : "${{ secrets.PG_SERVER_URL }}"
          PG_ACOUNT_USER     : "${{ secrets.PG_ACOUNT_USER }}"
          PG_ACOUNT_PASSWORD : "${{ secrets.PG_ACOUNT_PASSWORD }}"
        run: |
          bash Script/Bash/Tester.sh
