
name: Excel
run-name: Excel File Test

on:
  
  schedule:
    # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule
    - cron:  '56 4  *  *  THU'
          #   │  │  │  │  │
          #   │  │  │  │  └─── day of the week  (0–6, SUN-SAT)
          #   │  │  │  └────── month            (1–12)
          #   │  │  └───────── day of the month (1–31)
          #   │  └──────────── hour             (0–23)
          #   └─────────────── minute           (0–59)

  push:
    # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#push
    branches:
      - 'main'
    paths:
      - 'Apache_POI/**.*'

  workflow_dispatch:

jobs:

  Apache-POI:
    
    runs-on: ubuntu-22.04
      ## https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories
      ## https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2204-Readme.md

    steps:
      
      - name: Checkout
        uses: actions/checkout@v4
          ## https://github.com/actions/checkout

      - name: Download Apache POI
        working-directory: Apache_POI/
        shell: bash
          ## https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_iddefaultsrunshell
        run: |
          bash download_poi.sh

      - name: Compile
        working-directory: Apache_POI/
        shell: bash
          ## https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_iddefaultsrunshell
        run: |
          bash compile.sh

      - name: Test
        working-directory: Apache_POI/
        shell: bash
          ## https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_iddefaultsrunshell
        run: |
          bash test_newexcel.sh

      - name: Upload New Microsoft Excel Worksheet
        uses: actions/upload-artifact@v4
          ## https://github.com/actions/upload-artifact
        with:
          name: New Microsoft Excel Worksheet
          path: |
            Apache_POI/local_xlsx/*.xlsx

      - name: Upload Apache POI
        uses: actions/upload-artifact@v4
          ## https://github.com/actions/upload-artifact
        with:
          name: Apache_POI
          path: |
            Apache_POI/local_jar/*.jar

