
name: LilyPond
run-name: LilyPond

on:
  
  schedule:
    # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule
    - cron:  '43 5  *  *  SAT'
          #   │  │  │  │  │
          #   │  │  │  │  └─── day of the week  (0–6, SUN-SAT)
          #   │  │  │  └────── month            (1–12)
          #   │  │  └───────── day of the month (1–31)
          #   │  └──────────── hour             (0–23)
          #   └─────────────── minute           (0–59)

  push:
    # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#push
    branches:
      - 'main'
    paths:
      - 'LilyPond/**.*'

  workflow_dispatch:

jobs:

  Get-Download-URL:
    runs-on: ubuntu-latest
      ## https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories
      ## https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2204-Readme.md
    # Map a step output to a job output
    outputs:
      dowload-linux: ${{ steps.step-output.outputs.URL_DOWNLOAD_LINUX }}
      dowload-windows: ${{ steps.step-output.outputs.URL_DOWNLOAD_WINDOWS }}
      dowload-mac: ${{ steps.step-output.outputs.URL_DOWNLOAD_MAC }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
          ## https://github.com/actions/checkout

      - name: Test
        working-directory: LilyPond/
        shell: bash
          ## https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_iddefaultsrunshell
        run: |
          bash Bash/Test.sh

      - id: step-output
        name: Get Download URL
        working-directory: LilyPond/
        shell: bash
          ## https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_iddefaultsrunshell
        run: |
          bash Bash/GetURL.sh

  Download-Package-Linux:
    runs-on: ubuntu-latest
      ## https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories
      ## https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2204-Readme.md
    needs: [Get-Download-URL]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
          ## https://github.com/actions/checkout

      - name: Download-Package
        working-directory: LilyPond/
        env:
          URL_PACKAGE: "${{ needs.Get-Download-URL.outputs.dowload-linux }}"
        shell: bash
          ## https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_iddefaultsrunshell
        run: |
          bash Bash/Download-Linux.sh

      - uses: actions/upload-artifact@v4
          ## https://github.com/actions/upload-artifact
        with:
          name: "${{ env.NAME_PACKAGE }}"
          path: "${{ env.FOLDER_ARTIFACT }}"

  Download-Package-Windows:
    runs-on: ubuntu-latest
      ## https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories
      ## https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2204-Readme.md
    needs: [Get-Download-URL]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
          ## https://github.com/actions/checkout

      - name: Download-Package
        working-directory: LilyPond/
        env:
          URL_PACKAGE: "${{ needs.Get-Download-URL.outputs.dowload-windows }}"
        shell: bash
          ## https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_iddefaultsrunshell
        run: |
          bash Bash/Download-Windows.sh

      - uses: actions/upload-artifact@v4
          ## https://github.com/actions/upload-artifact
        with:
          name: "${{ env.NAME_PACKAGE }}"
          path: "${{ env.FOLDER_ARTIFACT }}"

  Download-Package-MacOS:
    runs-on: macos-latest
      ## https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories
      ## https://github.com/actions/runner-images/blob/main/images/macos/macos-14-Readme.md
    needs: [Get-Download-URL]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
          ## https://github.com/actions/checkout

      - name: Download-Package
        working-directory: LilyPond/
        env:
          URL_PACKAGE: "${{ needs.Get-Download-URL.outputs.dowload-mac }}"
        shell: bash
          ## https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_iddefaultsrunshell
        run: |
          bash Bash/Download-Linux.sh

      - uses: actions/upload-artifact@v4
          ## https://github.com/actions/upload-artifact
        with:
          name: "${{ env.NAME_PACKAGE }}"
          path: "${{ env.FOLDER_ARTIFACT }}"

  Generate-File-Linux:
    runs-on: ubuntu-latest
      ## https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories
      ## https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2204-Readme.md
    needs: [Download-Package-Linux]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
          ## https://github.com/actions/checkout

      - uses: actions/download-artifact@v4
          ## https://github.com/actions/download-artifact
        with:
          pattern: lilypond-*-linux-x86_64
          path: LilyPond/Package/

      - name: SetUp
        working-directory: LilyPond/
        shell: bash
          ## https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_iddefaultsrunshell
        run: |
          subfolder=$(
            ls --directory Package/lilypond-*/bin/ |
            head --lines=1
          )
          PATH_LILYPOND="${PWD%/}/${subfolder%/}/"
          PATH="${PATH}:${PATH_LILYPOND%/}"
          chmod u+x "${PATH_LILYPOND%/}/*"
          lilypond --version
          lilypond --help
          if [[ -n "${GITHUB_ENV}" ]]
          then
            echo "PATH_LILYPOND=${PATH_LILYPOND}"
            echo "PATH_LILYPOND=${PATH_LILYPOND}" >> "${GITHUB_ENV}"
            echo "PATH=${PATH}"
            echo "PATH=${PATH}"                   >> "${GITHUB_ENV}"
          fi


