
name: PostgreSQL
run-name: PostgreSQL

on:
  
  schedule:
    # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule
    - cron:  '45 6  *  *  SAT'
          #   │  │  │  │  │
          #   │  │  │  │  └─── day of the week  (0–6, SUN-SAT)
          #   │  │  │  └────── month            (1–12)
          #   │  │  └───────── day of the month (1–31)
          #   │  └──────────── hour             (0–23)
          #   └─────────────── minute           (0–59)

  push:
    # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#push
    branches:
      - 'main'
    paths:
      - 'PostgreSQL/**.*'

  workflow_dispatch:

jobs:

  Download-JDBC:
    
    runs-on: ubuntu-22.04
      ## https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories
      ## https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2204-Readme.md

    steps:
      
      - name: Checkout
        uses: actions/checkout@v4
          ## https://github.com/actions/checkout

      - name: Get Download URL
        working-directory: PostgreSQL/JDBC/
        shell: bash
          ## https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_iddefaultsrunshell
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            ## https://docs.github.com/en/actions/security-for-github-actions/security-guides/automatic-token-authentication#using-the-github_token-in-a-workflow
        run: |
          bash Bash/Download_URL.sh

      - name: Download
        working-directory: PostgreSQL/JDBC/
        shell: bash
          ## https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_iddefaultsrunshell
        run: |
          FOLDER_ART='Artifact/'
          mkdir --parent "${FOLDER_ART}"
          FILE_NAME="${URL_DOWNLOAD##*/}"
          FILE_SAVE="${FOLDER_ART%/}/${FILE_NAME}"
          curl --output "${FILE_SAVE}" --location "${URL_DOWNLOAD}"

      - uses: actions/upload-artifact@v4
        with:
          name: postgresql-jdbc-latest
          path: PostgreSQL/JDBC/Artifact/

