
name: Java (Linux)

on:
  
  schedule:
    # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule
    - cron:  '23 1 * * SUN'
  
  push:
    # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#push
    branches:
      - 'main'
    paths:
      - 'Java/**.*'

  workflow_dispatch:

jobs:
  
  "Pre-Check":
    
    runs-on: ubuntu-22.04
    ## https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories
    ## https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2204-Readme.md

    steps:
      
      - name: Checkout
        uses: actions/checkout@v4
        ## https://github.com/actions/checkout

      - name: Run a multi-line script
        working-directory: ./Java/
        run: |
          pwd
