
name: Java (Linux)

on:
  
  schedule:
    # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule
    - cron:  '23 1  *  *  SUN'
          #   │  │  │  │  │
          #   │  │  │  │  └─── day of the week  (0–6, SUN-SAT)
          #   │  │  │  └────── month            (1–12)
          #   │  │  └───────── day of the month (1–31)
          #   │  └──────────── hour             (0–23)
          #   └─────────────── minute           (0–59)
  
  push:
    # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#push
    branches:
      - 'main'
    paths:
      - 'Java/**.*'

  workflow_dispatch:
    inputs:
      version:
        type: choice
        description: Java Version
        required: false
        default: '21'
        options: 
        - '21'
        - '17'
        - '11'
      vendor:
        type: choice
        description: Vendor
        required: false
        default: 'Temurin'
        options: 
        - 'Temurin'
        - 'OpenJDK'
        - 'Oracle'
        - 'Corretto'
        - 'Microsoft'

jobs:
  
  Pre-Check:
    
    runs-on: ubuntu-22.04
    ## https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories
    ## https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2204-Readme.md

    steps:
      
      - name: Checkout
        uses: actions/checkout@v4
        ## https://github.com/actions/checkout

      - name: Run Pre-Check Scripts
        working-directory: ./Java/
        run: |
          ls 011_Linux_PreCheck/*.sh |
            while read -r shellfile
            do
              echo "Executing ${shellfile}"
              bash "${shellfile}"
            done
      
      - name: Run Check Scripts
        working-directory: ./Java/
        run: |
          ls 013_Linux_Check/*.sh |
            while read -r shellfile
            do
              echo "Executing ${shellfile}"
              bash "${shellfile}"
            done
  
  Java_Jobs:
    
    runs-on: ubuntu-22.04
    ## https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories
    ## https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2204-Readme.md

    steps:
      
      - name: Checkout
        uses: actions/checkout@v4
        ## https://github.com/actions/checkout

      - name: Get Download Link
        working-directory: ./Java/
        env:
          VERSION_JAVA : "${{ github.event.inputs.version || '21' }}"
          VENDOR_JAVA  : "${{ github.event.inputs.vendor  || 'Temurin' }}"
        run: |
          shellfile='015_Jobs/Get_URL.sh'
          echo "Executing ${shellfile}"
          bash "${shellfile}"

      - name: Download Java
        working-directory: ./Java/
        env:
          VERSION_JAVA : "${{ github.event.inputs.version || '21' }}"
          VENDOR_JAVA  : "${{ github.event.inputs.vendor  || 'Temurin' }}"
        run: |
          shellfile='015_Jobs/Installation.sh'
          echo "Executing ${shellfile}"
          bash "${shellfile}"

      - name: Post-check
        working-directory: ./Java/
        run: |
          ls 013_Linux_Check/*.sh |
            while read -r shellfile
            do
              echo "Executing ${shellfile}"
              bash "${shellfile}"
            done

  Pre-Check-MacOS:
    
    runs-on: macos-12
    ## https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories
    ## https://github.com/actions/runner-images/blob/main/images/macos/macos-12-Readme.md

    steps:
      
      - name: Checkout
        uses: actions/checkout@v4
        ## https://github.com/actions/checkout

      - name: Run Pre-Check Scripts
        working-directory: ./Java/
        run: |
          ls 011_Linux_PreCheck/*.sh |
            while read -r shellfile
            do
              echo "Executing ${shellfile}"
              bash "${shellfile}"
            done