
name: Node
run-name: Node Jobs

on:
  
  schedule:
    # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule
    - cron:  '45 3  *  *  MON'
          #   │  │  │  │  │
          #   │  │  │  │  └─── day of the week  (0–6, SUN-SAT)
          #   │  │  │  └────── month            (1–12)
          #   │  │  └───────── day of the month (1–31)
          #   │  └──────────── hour             (0–23)
          #   └─────────────── minute           (0–59)

  push:
    # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#push
    branches:
      - 'main'
    paths:
      - 'Node/**.*'

  workflow_dispatch:

jobs:

  Recommanded-Version:
    
    runs-on: ubuntu-latest
      ## https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories
      ## https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2404-Readme.md

    steps:
      
      - name: Checkout
        uses: actions/checkout@v4
          ## https://github.com/actions/checkout

      - name: Get Releases Data
        working-directory: Node/
        shell: bash
          ## https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_iddefaultsrunshell
        run: |
          bash Bash/Check-Releases.sh

      - name: Upload Artifact - Releases
        uses: actions/upload-artifact@v4
          ## https://github.com/actions/upload-artifact
        with:
          name: Releases
          path: |
            Node/Releases/*.*

