
name: LilyPond
run-name: LilyPond

on:
  
  schedule:
    # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule
    - cron:  '43 5  *  *  SAT'
          #   │  │  │  │  │
          #   │  │  │  │  └─── day of the week  (0–6, SUN-SAT)
          #   │  │  │  └────── month            (1–12)
          #   │  │  └───────── day of the month (1–31)
          #   │  └──────────── hour             (0–23)
          #   └─────────────── minute           (0–59)

  push:
    # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#push
    branches:
      - 'main'
    paths:
      - 'LilyPond/**.*'

  workflow_dispatch:
    inputs:
      ## https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories
      system-linux:
        description: 'Linux Version'
        
        required: true
        default: 'windows-latest'
        type: choice
        options:
        - ubuntu-latest
        - ubuntu-24.04
        - ubuntu-22.04
        - ubuntu-20.04
      system-windows:
        description: 'Windows Version'
        required: true
        default: 'ubuntu-latest'
        type: choice
        options:
        - windows-latest
        - windows-2022
        - windows-2019
      system-macos:
        description: 'MacOS Version'
        required: true
        default: 'macos-latest'
        type: choice
        options:
        - macos-latest
        - macos-14
        - macos-13
        - macos-12

jobs:

  Get-Download-URL:
    runs-on: ${{ inputs.system-linux || 'ubuntu-latest' }}
      ## https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories
      ## https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2204-Readme.md
    # Map a step output to a job output
    outputs:
      dowload-linux: ${{ steps.step-output.outputs.URL_DOWNLOAD_LINUX }}
      dowload-windows: ${{ steps.step-output.outputs.URL_DOWNLOAD_WINDOWS }}
      dowload-macos: ${{ steps.step-output.outputs.URL_DOWNLOAD_MAC }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
          ## https://github.com/actions/checkout

      - name: Test
        working-directory: LilyPond/
        shell: bash
          ## https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_iddefaultsrunshell
        run: |
          bash Bash/Test-Linux.sh

      - id: step-output
        name: Get Download URL
        working-directory: LilyPond/
        shell: bash
          ## https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_iddefaultsrunshell
        run: |
          bash Bash/GetURL.sh

  Download-Package-Linux:
    runs-on: ${{ inputs.system-linux || 'ubuntu-latest' }}
      ## https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories
      ## https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2204-Readme.md
    needs: [Get-Download-URL]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
          ## https://github.com/actions/checkout

      - name: Download-Package
        working-directory: LilyPond/
        env:
          URL_PACKAGE: "${{ needs.Get-Download-URL.outputs.dowload-linux }}"
        shell: bash
          ## https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_iddefaultsrunshell
        run: |
          bash Bash/Download-Linux.sh

      - name: SetUp
        working-directory: LilyPond/
        shell: bash
          ## https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_iddefaultsrunshell
        run: |
          bash Bash/SetUp-Linux.sh

      - name: Generate-File
        working-directory: LilyPond/
        shell: bash
          ## https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_iddefaultsrunshell
        run: |
          bash Bash/Generate-Linux.sh

      - uses: actions/upload-artifact@v4
          ## https://github.com/actions/upload-artifact
        with:
          name: "${{ env.NAME_PACKAGE }}"
          path: "${{ env.FOLDER_ARTIFACT }}"

      - uses: actions/upload-artifact@v4
          ## https://github.com/actions/upload-artifact
        with:
          name: output-linux
          path: LilyPond/Output/

  Download-Package-Windows:
    runs-on: ${{ inputs.system-windows || 'windows-latest' }}
      ## https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories
      ## https://github.com/actions/runner-images/blob/main/images/windows/Windows2022-Readme.md
    needs: [Get-Download-URL]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
          ## https://github.com/actions/checkout

      - name: Test
        working-directory: LilyPond/
        shell: cmd
          ## https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_iddefaultsrunshell
        run: |
          CMD\Test.cmd

      - name: Download-Package
        working-directory: LilyPond/
        env:
          URL_PACKAGE: "${{ needs.Get-Download-URL.outputs.dowload-windows }}"
        shell: cmd
          ## https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_iddefaultsrunshell
        run: |
          CMD\Download.cmd

      - name: SetUp
        working-directory: LilyPond\
        shell: cmd
          ## https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_iddefaultsrunshell
        run: |
          CMD\SetUp.cmd

      - name: Generate-File
        working-directory: LilyPond\
        shell: cmd
          ## https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_iddefaultsrunshell
        run: |
          CMD/Generate.cmd

      - name: Time Check
        working-directory: LilyPond\
        shell: cmd
          ## https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_iddefaultsrunshell
        run: |
          WMIC OS GET LocalDateTime

      - uses: actions/upload-artifact@v4
          ## https://github.com/actions/upload-artifact
        with:
          name: "${{ env.NAME_PACKAGE }}"
          path: "${{ env.FOLDER_ARTIFACT }}"

      - uses: actions/upload-artifact@v4
          ## https://github.com/actions/upload-artifact
        with:
          name: output-windows
          path: LilyPond/Output/

  Download-Package-MacOS:
    runs-on: ${{ inputs.system-macos || 'macos-latest' }}
      ## https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories
      ## https://github.com/actions/runner-images/blob/main/images/macos/macos-14-Readme.md
    needs: [Get-Download-URL]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
          ## https://github.com/actions/checkout

      - name: Test
        working-directory: LilyPond/
        shell: bash
          ## https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_iddefaultsrunshell
        run: |
          bash Bash/Test-MacOS.sh

      - name: Download-Package
        working-directory: LilyPond/
        env:
          URL_PACKAGE: "${{ needs.Get-Download-URL.outputs.dowload-macos }}"
        shell: bash
          ## https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_iddefaultsrunshell
        run: |
          bash Bash/Download-MacOS.sh

      - name: SetUp
        working-directory: LilyPond/
        shell: bash
          ## https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_iddefaultsrunshell
        run: |
          bash Bash/SetUp-MacOS.sh

      - name: Generate-File
        working-directory: LilyPond/
        shell: bash
          ## https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_iddefaultsrunshell
        run: |
          bash Bash/Generate-MacOS.sh

      - uses: actions/upload-artifact@v4
          ## https://github.com/actions/upload-artifact
        with:
          name: "${{ env.NAME_PACKAGE }}"
          path: "${{ env.FOLDER_ARTIFACT }}"

      - uses: actions/upload-artifact@v4
          ## https://github.com/actions/upload-artifact
        with:
          name: output-macos
          path: LilyPond/Output/

  Check-Package-Linux:
    runs-on: ${{ inputs.system-linux || 'ubuntu-latest' }}
      ## https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories
      ## https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2204-Readme.md
    needs: [Download-Package-Linux]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
          ## https://github.com/actions/checkout

      - uses: actions/download-artifact@v4
          ## https://github.com/actions/download-artifact
        with:
          pattern: lilypond-*-linux-x86_64
          path: LilyPond/Package/

      - name: SetUp
        working-directory: LilyPond/
        shell: bash
          ## https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_iddefaultsrunshell
        run: |
          bash Bash/SetUpFix-Linux.sh

      - name: Generate-File
        working-directory: LilyPond/
        shell: bash
          ## https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_iddefaultsrunshell
        run: |
          bash Bash/Generate-Linux.sh

      - uses: actions/upload-artifact@v4
          ## https://github.com/actions/upload-artifact
        with:
          name: test-linux
          path: LilyPond/Output/

  Check-Package-Windows:
    runs-on: ${{ inputs.system-windows || 'windows-latest' }}
      ## https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories
      ## https://github.com/actions/runner-images/blob/main/images/windows/Windows2022-Readme.md
    needs: [Download-Package-Windows]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
          ## https://github.com/actions/checkout

      - uses: actions/download-artifact@v4
          ## https://github.com/actions/download-artifact
        with:
          pattern: lilypond-*-mingw-x86_64
          path: LilyPond\Package\

      - name: Time Check
        working-directory: LilyPond\
        shell: cmd
          ## https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_iddefaultsrunshell
        run: |
          WMIC OS GET LocalDateTime

      - name: SetUp
        working-directory: LilyPond\
        shell: cmd
          ## https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_iddefaultsrunshell
        run: |
          CMD\SetUpFix.cmd

      - name: Generate-File
        working-directory: LilyPond\
        shell: cmd
          ## https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_iddefaultsrunshell
        run: |
          CMD/Generate.cmd

      - uses: actions/upload-artifact@v4
          ## https://github.com/actions/upload-artifact
        with:
          name: test-windows
          path: LilyPond/Output/

  Check-Package-MacOS:
    runs-on: ${{ inputs.system-macos || 'macos-latest' }}
      ## https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories
      ## https://github.com/actions/runner-images/blob/main/images/macos/macos-14-Readme.md
    needs: [Download-Package-MacOS]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
          ## https://github.com/actions/checkout

      - uses: actions/download-artifact@v4
          ## https://github.com/actions/download-artifact
        with:
          pattern: lilypond-*-darwin-x86_64
          path: LilyPond/Package/

      - name: SetUp
        working-directory: LilyPond/
        shell: bash
          ## https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_iddefaultsrunshell
        run: |
          bash Bash/SetUpFix-MacOS.sh

      - name: Generate-File
        working-directory: LilyPond/
        shell: bash
          ## https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_iddefaultsrunshell
        run: |
          bash Bash/Generate-MacOS.sh

      - uses: actions/upload-artifact@v4
          ## https://github.com/actions/upload-artifact
        with:
          name: test-macos
          path: LilyPond/Output/
